NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.sellerbank.letterofcredit.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.sellerbank.letterofcredit.com-cert.pem
    OrganizationalUnitIdentifier: peer
